- name: Detect Desktop Environment (Process Based)
  hosts: DPDYPH1FGLA0676, DPDYPH1FGLA0677, DPDYCC1FDRE0695, DPDYPH1FGLA0678, DPDYCC1FMRD0697, DPDYCC1FDRE0696, DPDYPH1FGLA0675, DPDYPH1FRET0688, DPDYPH1FRET0689, DPDYPHGFENQ0680
  become: yes
  gather_facts: false

  tasks:

    - name: Detect desktop via process
      shell: |
        if ps -e | grep -q "[c]innamon"; then
          echo cinnamon
        elif ps -e | grep -q "[g]nome-shell"; then
          echo gnome
        elif ps -e | grep -q "[x]fce4-session"; then
          echo xfce
        elif ps -e | grep -q "[p]lasmashell"; then
          echo kde
        else
          echo unknown
        fi
      register: desktop_env

    - name: Show detected desktop
      debug:
        msg: "Desktop Environment: {{ desktop_env.stdout }}"
