- name: Detect Desktop Environment (Process Based)
  hosts: DTUTFHGFREF0032, DTUTPHGFHIT0046, DTUTPHGFOPT0002, DTUTPHGFTEL0016, TTUTPHGFREF0014, TTUTPHGFREF0015, DTUTPH1FWRD0038, DTUTPHGFMRD0005, DTUTPHGFREG0017, TTUTPHGFOPD0025, TTUTPHGFREF0012, DTUTFHGFHIT0044, DTUTPHGFCOU0028, DTUTPH1FTHE0029, DTUTPHGFOPD0020, DTUTPHGFOPD0021, TTUTPHGFINV00
  become: yes
  gather_facts: false

  tasks:

    - name: Detect desktop via process
      shell: |
        if ps -e | grep -q "[c]innamon"; then
          echo cinnamon
        elif ps -e | grep -q "[g]nome-shell"; then
          echo gnome
        elif ps -e | grep -q "[x]fce4-session"; then
          echo xfce
        elif ps -e | grep -q "[p]lasmashell"; then
          echo kde
        else
          echo unknown
        fi
      register: desktop_env

    - name: Show detected desktop
      debug:
        msg: "Desktop Environment: {{ desktop_env.stdout }}"
