---
- name: Enforce XFCE Theme Restrictions
  hosts: DCHNICARESTDBYL, DCHNPH1FU1R0003, DCHNPH1FU1I0011, DCHNPH1FU2IN001, DCHNPH1FU3RE004, TCHNPH1FU010132, TCHNPH1FU1R0006, TCHNPH1FU1R0009, TCHNPH1FU2R0009, TCHNPH1FU2RE002, TCHNPH1FU2RE001
  become: yes
  gather_facts: no

  tasks:

    # =============================
    # 🔍 Detect XFCE Installed
    # =============================

    - name: Check XFCE installed
      shell: dpkg -l | grep -w xfce4-session
      register: xfce_check
      ignore_errors: yes
      changed_when: false

    - name: Show XFCE detection result
      debug:
        msg: "XFCE: {{ 'YES' if xfce_check.rc == 0 else 'NO' }}"

    # =============================
    # 🟡 XFCE RESTRICTIONS
    # =============================

    - name: Disable XFCE appearance settings
      when: xfce_check.rc == 0
      file:
        path: /usr/bin/xfce4-appearance-settings
        mode: '0644'

    - name: Disable XFCE window manager settings
      when: xfce_check.rc == 0
      file:
        path: /usr/bin/xfwm4-settings
        mode: '0644'
