---
- name: Enforce XFCE Theme Restrictions
  hosts: FH-2, TMDUFHGFRELAB31, DMDUFHGFDOC0008, DMDUFHGFDOC0018, TMDUFHGFREINV30, TMDUFHGFPRE0008, TMDUFH2FGLDOC62, TMDUPH4FSTBY022, DMDUFH3FINV0091, TMDUFHGFVIS0005, TMDUFHGFVIS0007, TMDUPH1FIOL0102, TMDUFHGFPRE0009, DMDUFHGFMRD0001, DMDUFH2FDOC0021, TMDUFHGFREF7010, TMDUFH2FREF0060, TMDUFH3FDOC0069
  become: yes
  gather_facts: no

  tasks:

    # =============================
    # 🔍 Detect XFCE Installed
    # =============================

    - name: Check XFCE installed
      shell: dpkg -l | grep -w xfce4-session
      register: xfce_check
      ignore_errors: yes
      changed_when: false

    - name: Show XFCE detection result
      debug:
        msg: "XFCE: {{ 'YES' if xfce_check.rc == 0 else 'NO' }}"

    # =============================
    # 🟡 XFCE RESTRICTIONS
    # =============================

    - name: Disable XFCE appearance settings
      when: xfce_check.rc == 0
      file:
        path: /usr/bin/xfce4-appearance-settings
        mode: '0644'

    - name: Disable XFCE window manager settings
      when: xfce_check.rc == 0
      file:
        path: /usr/bin/xfwm4-settings
        mode: '0644'
