---
- name: Enforce XFCE Theme Restrictions
  hosts: TMDUPH3FCOR0432, TMDUPH3FCORN001, TMDUPH3FCORN004, TMDUPH3FCORN003, TMDUPH3FCORN002, TMDUPH3FGLA0432, TMDUPH3FGLA0365, TMDUPH3FGLA03777, TMDUPH3FGLA0375, TMDUPH3FGLA0390, TMDUPH3FGLA0300, TMDUPH3FGLA0002, TMDUPH3FGLA0426, TMDUPH3FGLINV01, TMDUPH3FGLA0121, DMDUPH3FGLA0362, TMDUPH3FGLA3003
  become: yes
  gather_facts: no

  tasks:

    # =============================
    # 🔍 Detect XFCE Installed
    # =============================

    - name: Check XFCE installed
      shell: dpkg -l | grep -w xfce4-session
      register: xfce_check
      ignore_errors: yes
      changed_when: false

    - name: Show XFCE detection result
      debug:
        msg: "XFCE: {{ 'YES' if xfce_check.rc == 0 else 'NO' }}"

    # =============================
    # 🟡 XFCE RESTRICTIONS
    # =============================

    - name: Disable XFCE appearance settings
      when: xfce_check.rc == 0
      file:
        path: /usr/bin/xfce4-appearance-settings
        mode: '0644'

    - name: Disable XFCE window manager settings
      when: xfce_check.rc == 0
      file:
        path: /usr/bin/xfwm4-settings
        mode: '0644'
